#
# configure the public and cluster networks for ceph
#

- hosts: osd1
  become: yes
  become_user: root
  vars_files:
    - site_vars.yml

  tasks:
    - name: ensure libnm-glib installed for ansible nmcli support
      yum:
        name: NetworkManager-glib
        state: present
      when: ansible_os_family == "RedHat" and ansible_lsb.major_release|int >= 7


    - name: create network interface
      shell: nmcli con add type vlan con-name "{{ item.conn_name }}" dev "{{ item.ifname }}" id {{ item.vlanid }} ip4 {{ item.ip4 }}
      with_items:
        "{{ nmcli_ethernet }}"

    - name: set jumbo frame mtu on ethernet interfaces
      nmcli:
         type: ethernet
         conn_name: "{{ item.ifname }}"
         ifname: "{{ item.ifname }}"
         mtu: 9000
         state: present
      with_items:
        "{{ nmcli_ethernet }}"

    - name: set jumbo frame mtu on vlan interfaces
      nmcli:
         type: vlan
         conn_name: "{{ item.conn_name }}"
         mtu: 9000
         state: present
      with_items:
        "{{ nmcli_ethernet }}"
